solon:
  app:
    group: hj-rminf
    name: hj-rminf-app
server:
  ip: 10.20.11.147
  port: 8081
  http.gzip.enable: true
server.webservices.path: "/rminf/services/"

solon.cloud.rabbitmq:
  server: "10.20.10.5:5672"    #服务地址
  username: ahbcht              #链接账号
  password: Bcht123            #链接密码
  exchangeName: BCHT.ITS.DATA
  topic: BCHT.ITS.DATA.TOPIC
RminfJgVehicleinfo:
  convert-image: true

# 文件存储路径
nop:
  file:
    store-dir: H:\\test3
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:./db/test
    username: sa
    password:
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # jdbc-url: jdbc:mysql://10.20.10.152:30007/hj-rminf?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    # username: root
    # password: bcht@123

solon.logging.appender:
  console:
    level: TRACE #可根据需要调整级别
    enable: true #是否启用
  file:
    level: INFO
    name: "logs/${solon.app.name}"
    rolling: "logs/${solon.app.name}_%d{yyyy-MM-dd}/%i.log"
    maxFileSize: "10 MB"
    maxHistory: "7"

solon.logging.logger:
  "root": #默认记录器配置
    level: INFO
  "io.netty":
    level: WARN
  "com.zaxxer.hikari":
    level: WARN
  "io.nop.dao":
    level: WARN
  "io.nop.core.lang.sql":
    level: WARN


solon.config.add: "./app.yml"
