
nop:
  debug: true
  auth:
    jwt:
      enc-key: 95576a93d8c14ad79c344dc8995e2671

    login:
      allow-create-default-user: true # 如果用户表为空，则自动创建缺省账户nop, 密码nop-test

    site-map:
      static-config-path: /hj/rminf/auth/app.action-auth.xml
      cache-timeout: 1s
      support-debug: true

    data-auth-config-path: /hj/rminf/auth/app.data-auth.xml

  web:
    validate-page-model: true

  orm:
    init-database-schema: true

  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:./db/test
    username: sa
    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    jdbc-url: jdbc:mysql://127.0.0.1:3306/dev?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    username: nop
#    password: nop-test

# 支持graphql __schema查询，
  graphql:
    schema-introspection:
      enabled: true

# devservices 会启用testcontainers来管理测试数据库
quarkus:
  devservices:
    enabled: false

  datasource:
    devservices:
      enabled: false

  http:
    host: 0.0.0.0
    cors: true
    port: 8080

  log:
    level: INFO

    category:
      "io.nop":
        level: INFO

    file:
      enable: false
      path: log/app.log
      #      # 输出格式
      #      format: %d{yyyy-MM-dd HH:mm:ss,SSS} %h %N[%i] %-5p [%c{3.}] (%t) %s%e%n
      #      # Indicates whether to log asynchronously
      async: true
      rotation:
        max-file-size: 100M
        max-backup-index: 300
        file-suffix: .yyyy-MM-dd

# vertx相关配置
vertx:
  http:
    port: 8081