
nop:
  debug: false
  auth:
    jwt:
      enc-key: d12a089db9c44528a3f148004f5af602

    login:
      allow-create-default-user: true # 如果用户表为空，则自动创建缺省账户nop, 密码nop-test

    site-map:
      static-config-path: /hj/rminf/auth/app.action-auth.xml
      cache-timeout: 1s
      support-debug: false

    data-auth-config-path: /hj/rminf/auth/app.data-auth.xml

  web:
    validate-page-model: true

  orm:
    init-database-schema: true

# 支持graphql __schema查询，
  graphql:
    schema-introspection:
      enabled: true
