name: Linux (aarch64)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: [ 'ubuntu-20.04' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install aarch64 Toolchain
        run: sudo apt update && sudo apt install g++-aarch64-linux-gnu qemu qemu-user qemu-user-static

      - name: GitHub Action for GraalVM JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21.0.1' # for a specific JDK 21;
          distribution: 'graalvm' # New 'distribution' option
          cache: maven
          
      - name: Build with Maven
        run: mvn -B install --file pom.xml

      - name: Build with Maven (app)
        run: |
          set MAVEN_OPTS="-Duser.language=UTF-8 -Dfile.encoding=UTF-8"
          cd hj-rminf-app
          mvn clean package --P native -file pom.xml --no-transfer-progress

      - name: Upload artifacts app
        uses: actions/upload-artifact@v3
        with:
          name: app-artifacts
          path: hj-rminf-app/target/
          if-no-files-found: error # 如果未找到文件，则报错
