name: Build for aarch64 with银河麒麟

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-20.04' ] # 假设银河麒麟系统兼容Ubuntu 20.04的workflow
        arch: [ 'aarch64' ] # 指定aarch64架构
    name: Build - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}-${{ matrix.arch }} # 指定运行器为aarch64架构

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-${{ matrix.arch }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-${{ matrix.arch }}-m2

      - name: Set up JDK for GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21.0.1'
          distribution: 'graalvm'
          cache: maven

      - name: Build with Maven
        run: mvn -B install --file pom.xml

      - name: Build with Maven (app)
        run: |
          export MAVEN_OPTS="-Duser.language=UTF-8 -Dfile.encoding=UTF-8"
          cd hj-rminf-app
          mvn clean package --P native --file pom.xml --no-transfer-progress

      - name: Upload artifacts app
        uses: actions/upload-artifact@v3
        with:
          name: app-artifacts
          path: hj-rminf-app/target/
          if-no-files-found: error