# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build windows native image1

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-2022

    steps:

      # 缓存Maven的本地仓库
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - uses: actions/checkout@v3 # 这是GitHub提供的一个动作（action），用于将代码从GitHub仓库检出到工作目录中。v3是该动作的版本号。
      - name: GitHub Action for GraalVM JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21.0.1' # for a specific JDK 21;
          distribution: 'graalvm' # New 'distribution' option
          cache: maven

      - name: Build with Maven
        run: |
          set MAVEN_OPTS="-Duser.language=UTF-8 -Dfile.encoding=UTF-8"
          mvn clean package --P native -file pom.xml --no-transfer-progress

      - name: Upload artifacts app
        uses: actions/upload-artifact@v3
        with:
          name: hj-rminf-app-artifacts
          path: target/hj-rminf.exe
          if-no-files-found: error # 如果未找到文件，则报错


      - name: Execute hj-rminf.exe
        run: ./target/hj-rminf.exe


    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
